name: Drinkr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.0
  auto_size_text: ^2.1.0
  path_provider: ^1.6.9
  show_up_animation: ^1.0.1
  animated_text_kit: ^2.1.0
  #audioplayer: 0.8.1
  #audioplayer_web: 0.7.1
  audioplayers: ^0.15.1
  http: ^0.12.1
  connectivity: ^0.4.8+6
  flutter_spinkit: ^4.1.2
  fluttertoast: 4.0.0
  shared_preferences: ^0.5.7+3
  firebase_admob: ^0.9.3+2
  app_review: ^1.1.2
  assorted_layout_widgets: ^1.1.1
  draggable_scrollbar: ^0.0.4
  circular_reveal_animation: ^1.1.5
  html: ^0.14.0+3
  sqflite: ^1.3.1
  path: ^1.4.0
  url_launcher: ^5.4.11

  flutter:
    sdk: flutter
  splashscreen:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/text/
    - assets/text/de/
    - assets/text/en/
    - assets/image/
    - google_fonts/
    - assets/i18n/
    - assets/licenses/

  fonts:
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/image/appicon.new.png"
  ios: true
